### PR TITLE
use zig package manager (requires master)

### PR DESCRIPTION
**Pull request by sreehax**
The zig package manager now allows you to use the package manager for non-zig projects, which is perfect in this case.

### CODE REVIEW

**Comment by kassane** [comment]
Wow! Thanks for the contribution.

---

Need to change CI/CD zig version.

**Review by kassane — CHANGES_REQUESTED** [review]
Change it
https://github.com/kassane/qml_zig/blob/64b686973086a465108f55bdc87ab14c2eb33861/.github/workflows/Linux.yml#L13-L15
https://github.com/kassane/qml_zig/blob/64b686973086a465108f55bdc87ab14c2eb33861/.github/workflows/MSYS.yml#L23-L26

**Comment by sreehax** [comment]
Fixed

**Comment by kassane** [comment]
Awesome contribution!

However, I'll wait for this issue in DOtherSide to be fixed.

You can see in the CI that clang gives an error.
- https://github.com/filcuc/dotherside/issues/119

**Comment by kassane** [comment]
Wait: https://github.com/ziglang/zig/milestone/23 (v0.12.0)

**Review by kassane — APPROVED** [review]

**Pull request merged**
